networks:
  transcendence:
    name: transcendence

volumes:
  sqlite-data:

services:
  # --- Secrets manager ---
  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    command: vault server -dev
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    networks: [transcendence]

  # --- PHP auth module ---
  php:
    image: php-fpm
    container_name: php-fpm
    build:
      context: ../cybersec/srcs/php
      dockerfile: Dockerfile
    volumes:
      - ../cybersec/srcs/php:/var/www/html
      - sqlite-data:/var/sqlite-data
    expose:
      - "9000"
    networks: [transcendence]

  # --- App backend ---
  backend:
    build:
      context: ../app/srcs/back
    container_name: backend
    expose:
      - "3000"
    working_dir: /app
    command: ["sh", "-lc", "npx prisma migrate deploy && npm run dev"]
    networks: [transcendence]
    # No need to mount frontend into backend; edge serves the SPA

  # (removed) Frontend build helper; not needed since static files are served directly by edge

  # --- App websocket ---
  websocket-pong:
    build:
      context: ../app
      dockerfile: Dockerfile.ws-pong
    container_name: websocket-pong
    expose:
      - "8081"
    working_dir: /app
    command: ["node", "ws-pong-server.js"]
    networks: [transcendence]

  edge:
    image: nginx-modsec
    container_name: nginx-modsec
    build:
      context: ../cybersec/srcs/nginx
      dockerfile: Dockerfile
    depends_on:
      - php
      - backend
      - websocket-pong
      - vault
      # - app-nginx        # uncomment if you proxy to app-nginx for the frontend
    ports:
      - "8443:443"        # expose HTTPS to host on 8443 to avoid conflicts
    volumes:
      - ../app/srcs/front:/usr/share/nginx/html:ro            # serve SPA static files
      - ../cybersec/srcs/php/app:/var/www/html                 # serve /auth assets
      - ../cybersec/srcs/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../cybersec/srcs/nginx/conf/modsecurity.conf:/opt/ModSecurity/modsecurity.conf:ro
      - ../cybersec/srcs/nginx/certs:/etc/nginx/certs:ro
      - ../cybersec/srcs/nginx/logs:/var/log/modsecurity

    networks: [transcendence]
