services:
  nginx:
    image: nginx-modsec
    container_name: nginx-modsec
    build: 
      context: ./srcs/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./srcs/php/app:/var/www/html
      - ./srcs/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./srcs/nginx/conf/modsecurity.conf:/opt/ModSecurity/modsecurity.conf
      - ./srcs/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./srcs/nginx/certs:/etc/nginx/certs
      - ./srcs/nginx/logs/modsec_audit.log:/var/log/modsecurity/modsec_audit.log
    depends_on:
      - php
    networks:
      - trancendence

  php:
    image: php-fpm
    container_name: php-fpm
    build: 
      context: ./srcs/php
      dockerfile: Dockerfile
    volumes:
      - ./srcs/php:/var/www/html
      - sqlite-data:/var/sqlite-data
    expose:
      - "9000"
    networks:
      - trancendence

  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -dev
    networks:
      - trancendence

volumes:
  sqlite-data:

networks:
  trancendence:
    name: trancendence